<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="OpenTK" Version="4.8.0" />
    <PackageReference Include="OpenTK.WinForms" Version="4.0.0-pre.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\THREE\THREE.OpenGL\THREE.OpenGL.csproj" />
    <ProjectReference Include="..\THREE\THREE\THREE.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Import Project="..\THREE\THREEExample\THREEExample.projitems" Label="Shared" />

</Project>