"""JR phase 3 acceptance tests: explicit arithmetic from manual 7.11.

No golden files or reference values generated by the production model.
"""

from fem.nonlinear.hysteresis import JRStiffnessReductionParams as Params


def parameters(**changes):
    values = dict(
        delta_1_pos=1.0,
        delta_2_pos=4.0,
        delta_3_pos=10.0,
        P_1_pos=10.0,
        P_2_pos=16.0,
        P_3_pos=22.0,
        delta_1_neg=1.0,
        delta_2_neg=4.0,
        delta_3_neg=10.0,
        P_1_neg=10.0,
        P_2_neg=16.0,
        P_3_neg=22.0,
        beta=0.0,
        K_min=0.1,
    )
    values.update(changes)
    return Params(**values)


def advance(model, state, delta):
    p, k, info = model.get_force_and_stiffness(delta, state)
    return model.update_state(delta, p, k, state, info)


def history(model, points):
    state = model.create_initial_state()
    for delta in points:
        state = advance(model, state, delta)
    return state
