<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Printing\**\*.cs;PrintInput.cs;PrintData.cs;IPrintable.cs;PrintableBase*.cs" />
    <EmbeddedResource Remove="Printing\**;PrintInput.cs;PrintData.cs;IPrintable.cs;PrintableBase*.cs;fonts\**" />
    <Content Remove="Printing\**;PrintInput.cs;PrintData.cs;IPrintable.cs;PrintableBase*.cs;fonts\**" />
    <None Remove="Printing\**;PrintInput.cs;PrintData.cs;IPrintable.cs;PrintableBase*.cs;fonts\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDF_Manager.Core\PDF_Manager.Core.csproj" />
    <ProjectReference Include="..\PDF_Manager.Rendering\PDF_Manager.Rendering.csproj" />
    <ProjectReference Include="..\PDF_Manager.Printing\PDF_Manager.Printing.csproj" />
  </ItemGroup>

</Project>
