<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDF_Manager\PDF_Manager.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties testdata_4test001_3入力データ_1json__JsonSchema="https://appsemble.app/api.json" /></VisualStudio></ProjectExtensions>

</Project>